# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            MS
tagline:          'Architecture'
description:      'Portfolio'
url:              http://somniumm.github.io

author:
  name:           'Meng S'
  url:            https://twitter.com/

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole

pages_list:       
  About: '/about'
  Engineering: '/engineering'
  Architecture: '/architecture'
  Archive: '/archive'
  