# Site settings
title: m.s.
email: sunmmm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  works, thoughts, advantures.

url:  http://somniumm.github.io # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  somniumm

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  adventures:
    output: true
    permalink: /adventures/:path/
  test:
    output: true
    permalink: /test/:path/




